# Generated by Django 6.0.2 on 2026-02-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('garage_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagesaleevent',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='garage_sale_events', to='core.location'),
            preserve_default=False,
        ),
    ]
